const fs = require('fs');
const path = require('path');

// Build strings from char codes to completely avoid any text transformation
const dot = String.fromCharCode(46);
const jio = ['java','io'].join(dot);
const jum = ['java','util','Map'].join(dot);
const jus = ['java','util','Set'].join(dot);
const juu = ['java','util','UUID'].join(dot);
const juc = ['java','util','concurrent','ConcurrentHashMap'].join(dot);
const juw = ['java','util','concurrent','CopyOnWriteArrayList'].join(dot);
const li = ['log','info'].join(dot);

const lines = [];
lines.push('package com.next2me.next2view.service;');
lines.push('');
lines.push('import org.slf4j.Logger;');
lines.push('import org.slf4j.LoggerFactory;');
lines.push('import org.springframework.stereotype.Service;');
lines.push('import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;');
lines.push('');
lines.push('import ' + jio + '.IOException;');
lines.push('import ' + jum + ';');
lines.push('import ' + jus + ';');
lines.push('import ' + juu + ';');
lines.push('import ' + juc + ';');
lines.push('import ' + juw + ';');
lines.push('');
lines.push('@Service');
lines.push('public class SseEmitterService {');
lines.push('');
lines.push('    private static final Logger log = LoggerFactory.getLogger(SseEmitterService.class);');
lines.push('    private static final long SSE_TIMEOUT = 300_000L;');
lines.push('');
lines.push('    private final Map<UUID, CopyOnWriteArrayList<SseEmitter>> emitters = new ConcurrentHashMap<>();');
lines.push('');
lines.push('    public SseEmitter subscribe(UUID userId) {');
lines.push('        SseEmitter emitter = new SseEmitter(SSE_TIMEOUT);');
lines.push('        emitters.computeIfAbsent(userId, k -> new CopyOnWriteArrayList<>()).add(emitter);');
lines.push('        emitter.onCompletion(() -> removeEmitter(userId, emitter));');
lines.push('        emitter.onTimeout(() -> removeEmitter(userId, emitter));');
lines.push('        emitter.onError(e -> removeEmitter(userId, emitter));');
lines.push('        try {');
lines.push('            emitter.send(SseEmitter.event().name("connected").data("{\\"status\\":\\"connected\\"}"));');
lines.push('        } catch (IOException e) {');
lines.push('            removeEmitter(userId, emitter);');
lines.push('        }');
lines.push('        ' + li + '("SSE subscribed: userId={}, active={}", userId, getConnectionCount(userId));');
lines.push('        return emitter;');
lines.push('    }');
lines.push('');
lines.push('    public void broadcast(UUID actorId, String eventData, Set<UUID> targetUserIds) {');
lines.push('        for (UUID targetUserId : targetUserIds) {');
lines.push('            if (targetUserId.equals(actorId)) {');
lines.push('                continue;');
lines.push('            }');
lines.push('            CopyOnWriteArrayList<SseEmitter> userEmitters = emitters.get(targetUserId);');
lines.push('            if (userEmitters == null || userEmitters.isEmpty()) {');
lines.push('                continue;');
lines.push('            }');
lines.push('            for (SseEmitter emitter : userEmitters) {');
lines.push('                try {');
lines.push('                    emitter.send(SseEmitter.event().name("activity").data(eventData));');
lines.push('                } catch (IOException e) {');
lines.push('                    removeEmitter(targetUserId, emitter);');
lines.push('                }');
lines.push('            }');
lines.push('        }');
lines.push('    }');
lines.push('');
lines.push('    private void removeEmitter(UUID userId, SseEmitter emitter) {');
lines.push('        CopyOnWriteArrayList<SseEmitter> userEmitters = emitters.get(userId);');
lines.push('        if (userEmitters != null) {');
lines.push('            userEmitters.remove(emitter);');
lines.push('            if (userEmitters.isEmpty()) {');
lines.push('                emitters.remove(userId);');
lines.push('            }');
lines.push('        }');
lines.push('    }');
lines.push('');
lines.push('    private int getConnectionCount(UUID userId) {');
lines.push('        CopyOnWriteArrayList<SseEmitter> list = emitters.get(userId);');
lines.push('        return list == null ? 0 : list.size();');
lines.push('    }');
lines.push('}');

const target = process.argv[2];
if (!target) { console.error('Usage: node patch-sse2.cjs <path>'); process.exit(1); }
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, lines.join('\n') + '\n', 'utf8');
console.log('DONE: ' + target);
