const fs = require('fs');
const content = [
  'package com.next2me.next2view.service;',
  '',
  'import org.slf4j.Logger;',
  'import org.slf4j.LoggerFactory;',
  'import org.springframework.stereotype.Service;',
  'import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;',
  '',
  'import java.io.IOException;',
  'import java.util.Map;',
  'import java.util.Set;',
  'import java.util.UUID;',
  'import java.util.concurrent.ConcurrentHashMap;',
  'import java.util.concurrent.CopyOnWriteArrayList;',
  '',
  '@Service',
  'public class SseEmitterService {',
  '',
  '    private static final Logger log = LoggerFactory.getLogger(SseEmitterService.class);',
  '    private static final long SSE_TIMEOUT = 300_000L;',
  '',
  '    private final Map<UUID, CopyOnWriteArrayList<SseEmitter>> emitters = new ConcurrentHashMap<>();',
  '',
  '    public SseEmitter subscribe(UUID userId) {',
  '        SseEmitter emitter = new SseEmitter(SSE_TIMEOUT);',
  '        emitters.computeIfAbsent(userId, k -> new CopyOnWriteArrayList<>()).add(emitter);',
  '        emitter.onCompletion(() -> removeEmitter(userId, emitter));',
  '        emitter.onTimeout(() -> removeEmitter(userId, emitter));',
  '        emitter.onError(e -> removeEmitter(userId, emitter));',
  '        try {',
  '            emitter.send(SseEmitter.event().name("connected").data("{\\"status\\":\\"connected\\"}"));',
  '        } catch (IOException e) {',
  '            removeEmitter(userId, emitter);',
  '        }',
  '        log.info("SSE subscribed: userId={}, active={}", userId, getConnectionCount(userId));',
  '        return emitter;',
  '    }',
  '',
  '    public void broadcast(UUID actorId, String eventData, Set<UUID> targetUserIds) {',
  '        for (UUID targetUserId : targetUserIds) {',
  '            if (targetUserId.equals(actorId)) {',
  '                continue;',
  '            }',
  '            CopyOnWriteArrayList<SseEmitter> userEmitters = emitters.get(targetUserId);',
  '            if (userEmitters == null || userEmitters.isEmpty()) {',
  '                continue;',
  '            }',
  '            for (SseEmitter emitter : userEmitters) {',
  '                try {',
  '                    emitter.send(SseEmitter.event().name("activity").data(eventData));',
  '                } catch (IOException e) {',
  '                    removeEmitter(targetUserId, emitter);',
  '                }',
  '            }',
  '        }',
  '    }',
  '',
  '    private void removeEmitter(UUID userId, SseEmitter emitter) {',
  '        CopyOnWriteArrayList<SseEmitter> userEmitters = emitters.get(userId);',
  '        if (userEmitters != null) {',
  '            userEmitters.remove(emitter);',
  '            if (userEmitters.isEmpty()) {',
  '                emitters.remove(userId);',
  '            }',
  '        }',
  '    }',
  '',
  '    private int getConnectionCount(UUID userId) {',
  '        CopyOnWriteArrayList<SseEmitter> list = emitters.get(userId);',
  '        return list == null ? 0 : list.size();',
  '    }',
  '}',
].join('\n');

const target = process.argv[2] || 'SseEmitterService.java';
fs.writeFileSync(target, content, 'utf8');
console.log('DONE: ' + target);
